# 数据存放路径
data_path: /media/lxhong/Datasets   

# 关键帧
key_frame_distance: 0.5 # 关键帧距离

# 优化
# optimize_step_with_key_frame: 10000 # 没有其他信息时，每隔 step 发送一次优化的位姿
optimize_step_with_gnss: 20 # 每累计 step 个 gnss 观测时，优化一次
optimize_step_with_loop: 5  # 每累计 step 个闭环约束时优化一次

g2o_param:
    odom_edge_noise: [0.5, 0.5, 0.5, 0.001, 0.001, 0.001] # 噪声：x y z yaw roll pitch
    close_loop_noise: [0.3, 0.3, 0.3, 0.001, 0.001, 0.001] # 噪声：x y z yaw roll pitch
    gnss_noise: [3.0, 3.0, 12.0] # 噪声：x y z
